#!/usr/bin/env bash
#Configure haproxy to allow taffic from web o1 and web 02
sudo apt update -y
sudo apt install -y haproxy
cat <<EOF | sudo tee  /etc/haproxy/haproxy.cfg
frontend http_front
     bind *:80
     default_backend web_back
backend web_back
     balance roundrobin
     server web-01 100.26.186.180:80 check
     server web-02 18.205.158.105:80 check
EOF
sudo service haproxy restart

