#!/usr/bin/env bash
#scrip that does redirection
sudo sed -i '/listen 80 default_server;/a\
	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx reload

